name: Top-Level Code Check

on:
  pull_request:
    branches:
      - Master


jobs:
  analyze_dag_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Analyze DAG Files
      run: |
        python top_level_code_DAGs/analyze_dags.py
      working-directory: ${{ github.workspace }}
      id: analyze

  display_results:
    needs: analyze_dag_files
    runs-on: ubuntu-latest
    steps:
    - name: Display Results
      run: echo "${{ steps.analyze.outputs.stdout }}"