name: Top-Level Code Check

on:
  pull_request:
    branches:
      - Master


jobs:
  addedFilesList:
    runs-on: ubuntu-latest
    outputs:
      addedfiles: ${{ steps.set-added-files.outputs.addedfiles }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Get list of newly added files
        id: set-added-files
        run: |
          added_files=$(git diff --name-only --diff-filter=A origin/${{ github.event.pull_request.base.ref }} HEAD | grep "^dags/" | jq -R -s -c 'split("\n")[:-1]' | jq -r '.[] | ("./" + .)')
          echo "::set-output name=addedfiles::${added_files}"

  analyze_dag_files:
    runs-on: ubuntu-latest
    needs: addedFilesList
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Python script to analyze added files
        id: run-python-script
        env:
          addedfiles: ${{ needs.addedFilesList.outputs.addedfiles }}
        run: |
          added_files_str="${{ env.addedfiles }}"
          files=($added_files_str)
          valid_files=()
          invalid_files=()
          for file in "${files[@]}"; do
            echo "Processing file: $file"
            python analyze_dags.py "$file" >> analyze_result.txt
          done

          cat analyze_result.txt
