name: Top-Level Code Check

on:
  pull_request:
    branches:
      - Master

jobs:
  analyze_dag_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check DAG File for Top-Level Code
      run: |
        if grep -q "^[^ ]" dags/top_level_code_check.py; then
          echo "DAG file contains top-level code. Failing workflow."
          exit 1
        else
          echo "DAG file does not contain top-level code. Workflow passed."
        fi