name: Top-Level Code Check

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - Master

jobs:
  analyze_python_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Analyze Python Files
      run: |
        python top_level_code_check/dags/top_level_code_check.py
      working-directory: ${{ github.workspace }}
