name: Top-Level Code Check

on:
  pull_request:
    branches:
      - Master

jobs:
  changedFilesList:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Get main branch
        run: |
          echo "main_branch=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          git fetch --no-tags --prune --depth=1 origin +refs/heads/${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}

      - name: Get list of newly added files
        run: |
          added_files=$(git diff --name-only --diff-filter=A origin/${{ github.event.pull_request.base.ref }} HEAD | uniq | jq -R -s -c 'split("\n")[:-1]' | jq -r '.[] | ("./" + .)')
          echo "added_files=$added_files" >> $GITHUB_ENV

  analyze_dag_files:
    runs-on: ubuntu-latest
    needs: changedFilesList
    if: always() # Always run this job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Analyze DAG Files
        run: |
          changed_files="${{ env.added_files }}"
          if [ -z "$changed_files" ]; then
            changed_files=()
          fi
          echo "changed_files=$changed_files" >> $GITHUB_ENV
