name: Top-Level Code Check

on:
  pull_request:
    branches:
      - Master
jobs:
  analyze_dag_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Analyze DAG Files
      id: analyze
      run: |
        python analyze_dags.py >> analyze_output.txt
        echo "********************"
        cat analyze_output.txt

  display_results:
    needs: analyze_dag_files
    runs-on: ubuntu-latest
    steps:
    - name: Display Results
      run: |
        echo "Valid files with top-level code:"
        grep "Valid files with top-level code:" analyze_output.txt -A 100 | tail -n +2
        echo ""
        echo "Invalid files:"
        grep "Invalid files:" analyze_output.txt -A 100 | tail -n +2
