name: Top-Level Code Check

on:
  pull_request:
    branches:
      - Master

jobs:
  analyze_dag_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Analyze DAG Files
      run: |
        python analyze_dags.py > analyze_output.txt
      working-directory: ${{ github.workspace }}
      id: analyze

  display_results:
    needs: analyze_dag_files
    runs-on: ubuntu-latest
    steps:
    - name: Read Analysis Output
      id: read_analysis_output
      run: echo "::set-output name=analysis_output::$(cat analyze_output.txt)"

    - name: Display Results
      run: |
        echo "Files without top-level code:"
        grep "Files without top-level code:" <<< "${{ steps.read_analysis_output.outputs.analysis_output }}"
        echo ""
        echo "Files with top-level code:"
        grep "Files with top-level code:" <<< "${{ steps.read_analysis_output.outputs.analysis_output }}"