name: Top-Level Code Check

on:
  pull_request:
    branches:
      - Master

jobs:
  changedFilesList:
    runs-on: ubuntu-latest
    outputs:
      added_files: ${{ steps.get-added-files.outputs.added_files }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Get list of newly added files
        id: get-added-files
        run: |
          added_files=$(git diff --name-only --diff-filter=A origin/${{ github.event.pull_request.base.ref }} HEAD | grep "^dags/" | jq -R -s -c 'split("\n")[:-1]' | jq -r '.[] | ("./" + .)')
          echo "added_files=$added_files" >> $GITHUB_ENV

  analyze_dag_files:
    runs-on: ubuntu-latest
    needs: changedFilesList
    if: always() # Always run this job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Print File Names
        run: |
          added_files="${{ env.added_files }}"
          IFS=' ' read -ra files <<< "$added_files"
          for file in "${files[@]}"; do
            echo "Processing file: $file"
            python analyze_dags.py "$file"
          done