name: Top-Level Code Check

on:
  pull_request:
    branches:
      - master

jobs:
  analyze_dag_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Analyze DAG Files
      id: analyze
      run: |
        python analyze_dags.py >> analyze_output.txt

    - name: Top-level File validation
      id: validation
      run: |
        cat analyze_output.txt
        invalid_files=$(grep "Invalid files:" analyze_output.txt -A 100 | tail -n +2)
        for file in $invalid_files; do
          echo "Adding note for invalid file: $file"
          gh pr comment "$(gh pr view --json title --jq '.title' | tr -d '\n')" --body "The file $file is invalid."
        done