name: Top-Level Code Check

on:
  pull_request:
    branches:
      - Master


jobs:
  changedFilesList: # Job that list changed files
    runs-on: ubuntu-latest
    outputs:
      changedfiles: ${{ steps.set-changed-files.outputs.changedfiles }} # generate output names changedfiles by using inner step output
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Get main branch
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}
      
      - name: Get list of changed files
        id: set-changed-files
        run: echo changedfiles=$(git diff --name-only --diff-filter=A origin/${{ github.event.pull_request.base.ref }} HEAD | uniq  | jq -R -s -c 'split("\n")[:-1]' | jq -r '.[] | ("./" + .)') >>$GITHUB_OUTPUT
      
      - name: Print files to be validated
        run: echo "${{steps.set-changed-files.outputs.changedfiles}}"

  analyze_dag_files:
    runs-on: ubuntu-latest
    needs: changedFilesList
    if: always() # Always run this job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Print File Names
        run: |
          added_files="${{ env.added_files }}"
          IFS=' ' read -ra files <<< "$added_files"
          for file in "${files[@]}"; do
            echo "Processing file: $file"
            python analyze_dags.py "$file"
          done