name: Top-Level Code Check

on:
  pull_request:
    branches:
      - Master
jobs:
  analyze_dag_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Analyze DAG Files
      id: analyze
      run: |
        python analyze_dags.py >> analyze_output.txt

    - name: Top-level File validation
      id: validation
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Set the GH_TOKEN environment variable
      run: |
        cat analyze_output.txt  # Display the content of analyze_output.txt for debugging
        # Parse analyze_output.txt to extract invalid filenames
        invalid_files=$(grep "Invalid files:" analyze_output.txt -A 100 | tail -n +2)
        # Add note for each invalid file
        for file in $invalid_files; do
          echo "Adding note for invalid file: $file"
          # Use GitHub CLI to add a comment to the pull request
          gh pr comment "$(gh pr view --json title --jq '.title' | tr -d '\n')" --body "The file $file is invalid."
        done