name: Top-Level Code Check

on:
  pull_request:
    branches:
      - Master



jobs:
  analyze_dag_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Pull Request
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }} # Checkout the head of the pull request

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Get Changed Files
      id: changed_files
      run: |
        git diff --name-only ${{ github.event.pull_request.base.sha }} >> changed_files.txt

    - name: Filter DAG Files
      id: dag_files
      run: |
        grep "dag/" changed_files.txt >> dag_files.txt || true

    - name: Analyze DAG Files
      id: analyze
      run: |
        python analyze_dags.py $(cat dag_files.txt)

    - name: Top-level File Validation
      id: validation
      if: steps.dag_files.outputs.stdout != '' # Only run if there are DAG files
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cat dag_files.txt  # Display the content of dag_files.txt for debugging
        # Parse dag_files.txt to extract DAG filenames
        dag_files=$(cat dag_files.txt)
        # Add static note comment for each DAG file
        for file in $dag_files; do
          echo "Adding comment for DAG file: $file"
          # Add a static note comment for the DAG file
          gh pr comment "$(gh pr view --json title --jq '.title' | tr -d '\n')" --body "Analyzing DAG file: $file."
        done