name: Top-Level Code Check

on:
  pull_request:
    branches:
      - Master

jobs:
  analyze_dag_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Analyze DAG Files
      run: |
        python analyze_dags.py >> $GITHUB_STATE

  display_results:
    runs-on: ubuntu-latest
    needs: analyze_dag_files
    steps:
    - name: Display Results
      run: |
        cat $GITHUB_STATE
